name = "testPkg"
uuid = "9b4b8fa1-9ac0-43e7-a9e8-87f92f8c98fa"
authors = ["Administrator "]
version = "0.2.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
FFTW = "1.6.0"